language: cpp

compiler:
  - gcc
  - clang

os: osx

osx_image: xcode7.3

before_install:
  - brew update
  - brew install cmake
  - brew install cpprestsdk
  - brew link --force openssl

script:
  - if [ "$CXX" = "g++" ]; then
      cmake . -DCMAKE_CXX_COMPILER=/Applications/Xcode-beta.app/Contents/Developer/usr/bin/g++ -DCMAKE_BUILD_TYPE=Release && make;
    else
      cmake . -DCMAKE_BUILD_TYPE=Release && make;
    fi
