language: cpp

compiler:
  - gcc
  - clang

os: osx

osx_image: xcode7.3

before_install:
  - brew update
  - brew install cmake
  - brew install cpprestsdk
  - brew link --force openssl
  - if [ "$CXX" = "g++" ]; then
      brew install gcc;
      CC=gcc-5 CXX=g++-5 CXXFLAGS=-nostdinc++ -I/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -nodefaultlibs -lc++ -lc++abi -lm -lc;
    fi

script:
  - cmake . -DCMAKE_BUILD_TYPE=Release && make
