language: cpp

compiler:
  - gcc
  - clang

os: osx

osx_image: xcode7.3

before_install:
  - brew update
  - brew install cmake
  - brew install cpprestsdk
  - brew link --force openssl

script:
  - cmake . -DCMAKE_BUILD_TYPE=Release && make -j4
